//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifyMeService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSettings
    {
        public int EmailSettingId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Host { get; set; }
        public string Port { get; set; }
        public string Limit { get; set; }
        public string MailAddress { get; set; }
    }
}
