//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifyMeService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotifyMeServiceEntities : DbContext
    {
        public NotifyMeServiceEntities()
            : base("name=NotifyMeServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NotifyMePlease> NotifyMePlease { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<SmsSettings> SmsSettings { get; set; }
        public virtual DbSet<EmailSettings> EmailSettings { get; set; }
        public virtual DbSet<ClientType> ClientType { get; set; }
    }
}
