//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifyMeService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyMePlease
    {
        public int NotifyMeServiceId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string NotifiyMeRequest { get; set; }
        public string NotifyMeResponse { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual ClientType ClientType { get; set; }
    }
}
